### ISSUE TITLE
Support for Jenkinsfile not named "Jenkinsfile"

### ISSUE THREAD

**Issue by EricSt-Amand-opalrt** [de-jcup/eclipse-jenkins-editor#31]
Hello,
Thanks for the plugin it is helpful!  Here is an improvement I would like to suggest.
I believe naming your Jenkinsfile "Jenkinsfile" is just a convention and is not mandatory.  It would be nice if the color rendering could be applied on files named other than "Jenkinsfile".  Maybe have some wildcard expression or regular expression in the preferences of Jenkins Editor plugin to match unconventional names ?
For example, in one of my project I have a jenkinsfile named "JenkinsfileMerge".  Eclipse is not seeing it as a true Jenkinsfile so its not applying the color scheme.

**Comment by de-jcup** [comment]
Hello @EricSt-Amand-opalrt ,

the easiest way to open files not named as `Jenkinsfile` is to do following steps:

![image](https://user-images.githubusercontent.com/11644753/36278377-f41c67de-1293-11e8-8991-7823c08559b0.png)

![image](https://user-images.githubusercontent.com/11644753/36278559-7e8444b4-1294-11e8-9f95-591a56fbf895.png)

Just press OK and your file is opened with `Jenkins Editor` as wanted.

Another way is to associate the filenames in preferences:
![image](https://user-images.githubusercontent.com/11644753/36278689-da2ee72e-1294-11e8-885e-22996616be3f.png)

**Comment by de-jcup** [comment]
@EricSt-Amand-opalrt 
I also added tjhe answert to your question to FAQ at 
https://github.com/de-jcup/eclipse-jenkins-editor/wiki/FAQ#how-can-i-open-other-files-than-jenkinsfile-with-jenkins-editor

Is the answer okay for you? Another option would be to integrate a behaviour like in bash-editor (see https://github.com/de-jcup/eclipse-bash-editor/wiki/Files-without-file-extension ) but this always not trivial, because jenkins files are not so easy to identify as bash files...

**Comment by EricSt-Amand-opalrt** [comment]
Great, that made it!  Thanks!  And good idea to stick that in the FAQ.  Closing the issue now,
