### ISSUE TITLE
Unable to install at Eclipse Photon over Marketplace

### ISSUE THREAD

**Issue by BerndDoser** [de-jcup/eclipse-jenkins-editor#38]
On the new release Eclipse Photon I get the error message:

Unable to read repository at https://dl.bintray.com/de-jcup/jenkinseditor/content.xml.
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

**Comment by de-jcup** [comment]
@BerndDoser 
 
`java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
`
content.xml is only tried to load when https://dl.bintray.com/de-jcup/jenkinseditor/content.jar is not found - but the content.jar **IS** available (I just tried it with my browser)

I also installed the plugin into a new downloaded eclipse photon via eclipse marketplace. Did work without any problems from my home location in germany using Open JDK 8 on Linux.

Reading
https://stackoverflow.com/questions/4764611/java-security-invalidalgorithmparameterexception-the-trustanchors-parameter-mus or
https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty
It seems this is an issue with your installed JRE. Please read the answers there or start your eclipse with alternative JRE which is containing correct cacerts and try again. If all goes wrong you could try to get it by `http` instead of `https` but ... I would not do this... 
 
Hope this helps

**Comment by BerndDoser** [comment]
Hi @de-jcup,

Thanks for your help. You are right. Only openjdk-11 shows this issue. openjdk-8 works fine.

**Comment by de-jcup** [comment]
Maybe the reason is that bintray has deprecated older TLS variants from 2018-06-24
see
https://jfrog.com/knowledge-base/why-am-i-failing-to-work-with-jfrog-saas-service-with-tls-1-0-1-1/
