### ISSUE TITLE
Allow user to select -ssh option for linter

### ISSUE THREAD

**Issue by turekg** [de-jcup/eclipse-jenkins-editor#82]
Hello, I am using the plugin in Eclipse 4.19.0 and I cannot make validation work at all either. The message is:
```
Connection test failed
Connection test to 'https://io-jenkins.mercator-ocean.fr' was NOT successful!

JenkinsLinterCLIResult:
- exitCode:-2 (Linter was not executed at all)
- failureMessage:Access to Jenkins was not possible by command:

java -jar /Users/gturek/tools/jenkins-cli.jar -http -auth gturek:******* declarative-linter 

Maybe credentials not valid or hostname/firewall problems.
Please check Jenkins CLI setup in preferences
-Output was:
```
Looking at the Jenkins logs I saw this:
```
java.io.IOException: HTTP full-duplex channel timeout: 54664710-2940-45f4-b7ea-34ac7423b49d
```
So it turns out that because my Jenkins instance is behind an Apache reverse proxy I cannot use the -http method for the Linter but I need to use the -ssh option. It would be nice if in Preferences the user would be allowed to select this option (in this case, he would need to specify the ssh port). Thank you!

**Comment by de-jcup** [comment]
API usage for ssh is described https://www.jenkins.io/doc/book/managing/cli/#ssh-connection-mode

**Comment by de-jcup** [comment]
With Version 1.8.0 it will be possible to select SSH authentication in preferences
![image](https://user-images.githubusercontent.com/11644753/117219747-30ff3300-ae06-11eb-92c4-0a21315b31ec.png)

For SSH connection the username must be defined in the credentials.
otherwise any command will show up like this:
![image](https://user-images.githubusercontent.com/11644753/117219942-95ba8d80-ae06-11eb-99ed-baecd0fa01fe.png)

**Comment by turekg** [comment]
Thanx! That works perfectly well
