### ISSUE TITLE
Error validating Jenkins file. "Output was" message is empty

### ISSUE THREAD

**Issue by Padmahas** [de-jcup/eclipse-jenkins-editor#88]
Hello,

I tried to provide wrong credentials intentionally and got proper error message on "Output was" section like
```
java.io.IOException: Server returned HTTP response code: 401 for URL: https://SOMEDOMAINNAME.com/cli?remoting=false
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:74)
	at hudson.cli.CLI.plainHttpConnection(CLI.java:374)
	at hudson.cli.CLI._main(CLI.java:312)
	at hudson.cli.CLI.main(CLI.java:96)
```

I checked clicking on "Test Connection" button after setting proper credentials and got "Success" dialog box.
But when I choose to validate the Jenkins file, with proper credentials, I'm getting below Exception, however the "-Output was" section is empty.

```
Jenkins CLI call failed.
JenkinsLinterCLIResult:
- exitCode:-2 (Linter was not executed at all)
- failureMessage:Access to Jenkins was not possible by command:

java -jar F:\sts-4.9.0.RELEASE\configuration\org.eclipse.osgi\933\0\.cp\lib\jenkins-cli.jar -s https://DOMAINNAME.com -http -auth USERNAME:******* declarative-linter 

Maybe credentials not valid or hostname/firewall problems.
Please check Jenkins CLI setup in preferences
-Output was:
```

Thank you.

**Comment by de-jcup** [comment]
## Initial questions
Have you installed latest version (1.8.0) ?

You have to press "Apply" at the preferences dialog to store your user-credentials. Otherwise they will not be used.
If you forget this and try to do a Jenkins linter call, version 1.8.0 will show up following dialog:

![image](https://user-images.githubusercontent.com/11644753/124025601-f0c8c500-d9f0-11eb-822c-071017c13555.png)

## How I tried to reproduce your problem

My test setup:
- Eclipse 2021-06
- Linux Mint 20.1
- Jenkins Editor Plugin 1.8.0
- used defaults preferences from editor plugin
 
0. Drop old security storage to have a clean situation
![image](https://user-images.githubusercontent.com/11644753/124027142-d0016f00-d9f2-11eb-9275-ffbd179b52bc.png)

I pressed "Delete" and followed instruction - which did also restart my eclipse instance

1. I started a new local jenkins by docker:
```
sudo docker run -p 8080:8080 jenkins/jenkins:lts
```
This started a Jenkins 2.277.4 by docker

2. After start was ready in console, i copied the inital token from log and opened http://localhost:8080 at my developer machine.
There I pasted the copied key and then entered my wanted credentials etc.
3. I clicked on "install recommended plugins"

After a short while my temporary jenkins was ready

4. I opened http://localhost:8080/user/$myUserIdEnteredBefore/configure and clicked on "add new token", typed "test-token" inside and pressed "Generate" button and remembered the given API-token
![image](https://user-images.githubusercontent.com/11644753/124026356-e1964700-d9f1-11eb-98d0-bbdd6b18a393.png)

5.  Opening preference page and enter my user-credentials
![image](https://user-images.githubusercontent.com/11644753/124026557-215d2e80-d9f2-11eb-9db4-9fa58791b06f.png)
pressed "OK" button. 
6. Pressed "Test connection button"
![image](https://user-images.githubusercontent.com/11644753/124026637-39cd4900-d9f2-11eb-9b13-c50ec1308d34.png)

7. Pressed now "Apply and close in Dialog"
![image](https://user-images.githubusercontent.com/11644753/124026706-4ce01900-d9f2-11eb-9010-961c41eb9fb3.png)

8. Secure storage dialog appears
![image](https://user-images.githubusercontent.com/11644753/124027426-279fda80-d9f3-11eb-9a60-cc5bdeeadecb.png)
and I said either "yes" or "no"

9. After this, I opened a jenkins file and pressed the jenkins linter icon inside toolbar (shows a  Jenkins with green check mark) . 
resulted in
![image](https://user-images.githubusercontent.com/11644753/124027665-6df53980-d9f3-11eb-9b4a-17f26f45956f.png)

10. Tried with context menu inside opened jenkins editor
![image](https://user-images.githubusercontent.com/11644753/124027944-ba407980-d9f3-11eb-8fd9-cac6df36f0e9.png)

Same as with 9: linter worked

11. Tried inside Jenkins Editor console:
![image](https://user-images.githubusercontent.com/11644753/124028430-3f2b9300-d9f4-11eb-8fa1-576980b6605d.png)

I pressed Icon on right corner (Execute CLI command)

![image](https://user-images.githubusercontent.com/11644753/124028465-4fdc0900-d9f4-11eb-9fe7-8ceb50414546.png)
A kept the "help" command and pressed "OK"
All commands where printed:
![image](https://user-images.githubusercontent.com/11644753/124028650-8b76d300-d9f4-11eb-81af-3bda9942e053.png)

12. tried "who am i" in jenkins editor console
![image](https://user-images.githubusercontent.com/11644753/124028698-97629500-d9f4-11eb-9603-346c73c316a1.png)
did also work well:
![image](https://user-images.githubusercontent.com/11644753/124028722-9f223980-d9f4-11eb-9539-be650baa212c.png)

## Conlusion
I was not able to reproduce your problem - but maybe the mentioned steps before did help you as well.
